version: 2

aliases:
  - &workspace
    at: ~/
  - &deps-cache
    keys:
      - v1-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - v1-deps-{{ .Branch }}-
  - &persist-build
    root: ~/
    paths:
      - release

env-node: &env-node
  working_directory: ~/release
  docker:
    - image: cimg/node:12.18.0
      environment:
        TERM: xterm

env-browser: &env-browser
  working_directory: ~/release
  docker:
    - image: cypress/browsers:node12.18.0-chrome83-ff77
      environment:
        TERM: xterm

jobs:
  bootstrap:
    <<: *env-node
    steps:
      - checkout
      - restore_cache: *deps-cache
      - run:
          name: Checking environment
          command: |
            node --version
            npm --version
            yarn --version
      - run:
          name: Installing dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Caching dependencies
          key: v1-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - .cache
      - persist_to_workspace:
          root: ~/
          paths:
            - .cache
            - release

  build:
    <<: *env-node
    steps:
      - attach_workspace: *workspace
      - restore_cache: *deps-cache
      - run:
          name: Linting
          command: yarn lint
      - run:
          name: Building the library
          command: yarn build
      - run:
          name: Previewing Service Worker script build
          command: cat lib/esm/mockServiceWorker.js
      - persist_to_workspace: *persist-build

  test-unit:
    <<: *env-node
    steps:
      - attach_workspace: *workspace
      - restore_cache: *deps-cache
      - run:
          name: Running unit tests
          command: yarn test:unit

  test-integration:
    <<: *env-browser
    steps:
      - attach_workspace: *workspace
      - restore_cache: *deps-cache
      - run:
          name: Running integration tests
          command: yarn test:integration

  test-smoke:
    <<: *env-browser
    steps:
      - attach_workspace: *workspace
      - restore_cache: *deps-cache
      - run:
          name: Checking environment
          command: |
            node --version
            npm --version
            yarn --version
      - run:
          name: Running smoke tests
          command: yarn test:smoke

workflows:
  version: 2
  release:
    jobs:
      - bootstrap

      - build:
          requires:
            - bootstrap
      - test-unit:
          requires:
            - bootstrap

      - test-integration:
          requires:
            - build
      - test-smoke:
          requires:
            - build
